name: MMST
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - asttokens=3.0.1
  - binutils_impl_linux-64=2.45
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2026.1.4
  - cairo=1.18.0
  - comm=0.2.3
  - contourpy=1.3.2
  - curl=8.17.0
  - cycler=0.12.1
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.1
  - executing=2.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gcc_impl_linux-64=15.2.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gfortran_impl_linux-64=15.2.0
  - graphite2=1.3.14
  - gxx_impl_linux-64=15.2.0
  - harfbuzz=8.3.0
  - icu=73.2
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.45
  - lerc=4.0.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.11.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcurl=8.17.0
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.78.1
  - libgomp=15.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libpng=1.6.53
  - libsanitizer=15.2.0
  - libsodium=1.0.20
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.1
  - libuuid=2.41.2
  - libwebp-base=1.6.0
  - libxcb=1.15
  - libzlib=1.3.1
  - make=4.4.1
  - matplotlib-base=3.10.8
  - munkres=1.1.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openjpeg=2.5.4
  - openssl=3.6.0
  - pandas=2.3.3
  - pango=1.50.14
  - parso=0.8.5
  - patsy=1.0.2
  - pcre2=10.40
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.1
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.0
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - pyzmq=27.1.0
  - qhull=2020.2
  - r-base=4.3.1
  - readline=8.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sed=4.9
  - six=1.17.0
  - somoclu=1.7.5
  - sqlite=3.51.1
  - stack_data=0.6.3
  - statsmodels=0.14.6
  - sysroot_linux-64=2.34
  - tk=8.6.13
  - tktable=2.10
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - tzdata=2025b
  - unicodedata2=17.0.0
  - wcwidth=0.2.14
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - affine==2.4.0
      - aiobotocore==2.5.4
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aioitertools==0.13.0
      - aiosignal==1.4.0
      - anndata==0.10.9
      - anywidget==0.9.18
      - array-api-compat==1.12.0
      - asciitree==0.3.3
      - async-timeout==5.0.1
      - attrs==25.4.0
      - bleach==6.3.0
      - bokeh==3.8.1
      - botocore==1.31.17
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - choreographer==1.2.1
      - click==8.3.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - cloudpickle==3.1.2
      - cmcrameri==1.9
      - colorcet==3.1.0
      - cython==3.1.4
      - dask==2024.4.2
      - dask-expr==1.0.14
      - dask-image==2024.5.3
      - datashader==0.18.2
      - distributed==2024.4.2
      - docrep==0.3.2
      - dpcpp-cpp-rt==2025.3.1
      - fasteners==0.20
      - filelock==3.20.0
      - fiona==1.10.1
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2023.6.0
      - geopandas==1.1.1
      - graphst==1.1.1
      - gudhi==3.11.0
      - h5py==3.15.1
      - idna==3.11
      - igraph==0.10.6
      - imageio==2.37.2
      - inflect==7.5.0
      - iniconfig==2.3.0
      - intel-cmplr-lib-rt==2025.3.1
      - intel-cmplr-lib-ur==2025.3.1
      - intel-cmplr-lic-rt==2025.3.1
      - intel-opencl-rt==2025.3.1
      - intel-openmp==2025.3.1
      - intel-sycl-rt==2025.3.1
      - ipywidgets==8.1.8
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.5.2
      - jupyter-bokeh==4.0.5
      - jupyterlab-widgets==3.0.16
      - kaleido==1.1.0
      - lazy-loader==0.4
      - legacy-api-wrap==1.5
      - leidenalg==0.10.2
      - linkify-it-py==2.0.3
      - llvmlite==0.45.1
      - locket==1.0.0
      - logistro==2.0.1
      - louvain==0.8.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.8.4
      - matplotlib-inline==0.1.7
      - matplotlib-scalebar==0.9.0
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - mkl==2025.2.0
      - mkl-fft==1.3.6
      - mkl-random==1.2.2
      - mkl-service==2.5.2
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multipledispatch==1.0.0
      - multiscale-spatial-image==2.0.2
      - narwhals==2.13.0
      - natsort==8.4.0
      - networkx==2.8.8
      - numba==0.62.1
      - numcodecs==0.13.1
      - numpy==1.25.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - ome-zarr==0.10.2
      - omnipath==1.0.12
      - orjson==3.11.5
      - packaging==26.0
      - panel==1.8.2
      - param==2.3.1
      - partd==1.4.2
      - pillow==12.1.0
      - pims==0.7
      - plotly==6.3.0
      - pluggy==1.6.0
      - pooch==1.8.2
      - pot==0.9.4
      - progress==1.6.1
      - propcache==0.4.1
      - psygnal==0.15.0
      - pyarrow==22.0.0
      - pycparser==2.23
      - pyct==0.6.0
      - pylib-openblas==0.0.2
      - pynndescent==0.5.13
      - pyogrio==0.12.1
      - pyparsing==3.3.2
      - pyproj==3.7.1
      - pytest==9.0.2
      - pytest-timeout==2.4.0
      - python-igraph==0.10.6
      - pytz-deprecation-shim==0.1.0.post0
      - pyviz-comms==3.0.6
      - pyyaml==6.0.3
      - rasterio==1.4.4
      - requests==2.32.5
      - rich==14.2.0
      - rpy2==3.5.17
      - s3fs==2023.6.0
      - scanpy==1.10.3
      - scikit-image==0.24.0
      - scikit-learn==1.3.2
      - scikit-misc==0.3.1
      - scipy==1.9.3
      - session-info==1.0.1
      - session-info2==0.2.3
      - setuptools==80.10.1
      - shapely==2.1.2
      - silhouette-spatial-score==0.1.0
      - simplejson==3.20.2
      - slicerator==1.1.0
      - somde==0.1.8
      - sortedcontainers==2.4.0
      - spagcn==1.2.7
      - spatial-image==1.2.1
      - spatialdata==0.2.6
      - squidpy==1.6.1
      - stdlib-list==0.12.0
      - sympy==1.14.0
      - tbb==2022.3.0
      - tblib==3.2.2
      - tcmlib==1.4.1
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tomli==2.3.0
      - toolz==1.1.0
      - torch==2.3.0
      - torch-cluster==1.6.3+pt23cu121
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt23cu121
      - torch-sparse==0.6.18+pt23cu121
      - torch-spline-conv==1.2.2+pt23cu121
      - torchaudio==2.3.0
      - torchvision==0.18.0
      - tqdm==4.67.1
      - triton==2.3.0
      - typeguard==4.4.4
      - tzlocal==4.3.1
      - uc-micro-py==1.0.3
      - umap-learn==0.5.7
      - umf==1.0.2
      - urllib3==1.26.20
      - validators==0.35.0
      - webencodings==0.5.1
      - wheel==0.46.3
      - widgetsnbextension==4.0.15
      - wrapt==1.17.3
      - xarray==2024.11.0
      - xarray-dataclass==3.0.0
      - xarray-dataclasses==1.9.1
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - xxhash==3.6.0
      - xyzservices==2025.11.0
      - yarl==1.22.0
      - zarr==2.16.1
      - zict==3.0.0
prefix: /home/accounts/personale/nndgpl46/miniconda3/envs/MMST
